import { Achievement } from './types'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_card',
    name: 'Premier pas',
    description: 'Révisez votre première carte',
    icon: '🌱',
    xpReward: 50,
    rarity: 'common',
    condition: (p) => p.totalCardsReviewed >= 1,
  },
  {
    id: 'ten_cards',
    name: 'Débutant motivé',
    description: 'Révisez 10 cartes',
    icon: '📚',
    xpReward: 100,
    rarity: 'common',
    condition: (p) => p.totalCardsReviewed >= 10,
  },
  {
    id: 'fifty_cards',
    name: 'Studieux',
    description: 'Révisez 50 cartes au total',
    icon: '🎓',
    xpReward: 200,
    rarity: 'common',
    condition: (p) => p.totalCardsReviewed >= 50,
  },
  {
    id: 'hundred_cards',
    name: 'Centurion',
    description: 'Révisez 100 cartes',
    icon: '💯',
    xpReward: 300,
    rarity: 'rare',
    condition: (p) => p.totalCardsReviewed >= 100,
  },
  {
    id: 'five_hundred',
    name: 'Marathonien',
    description: 'Révisez 500 cartes',
    icon: '🏃',
    xpReward: 600,
    rarity: 'rare',
    condition: (p) => p.totalCardsReviewed >= 500,
  },
  {
    id: 'thousand_cards',
    name: 'Érudit',
    description: 'Révisez 1000 cartes',
    icon: '🏛️',
    xpReward: 1000,
    rarity: 'epic',
    condition: (p) => p.totalCardsReviewed >= 1000,
  },
  {
    id: 'streak_3',
    name: 'Régulier',
    description: '3 jours consécutifs de révision',
    icon: '🔥',
    xpReward: 75,
    rarity: 'common',
    condition: (p) => p.streak >= 3,
  },
  {
    id: 'streak_7',
    name: 'Une semaine entière',
    description: '7 jours consécutifs',
    icon: '🔥🔥',
    xpReward: 200,
    rarity: 'rare',
    condition: (p) => p.streak >= 7,
  },
  {
    id: 'streak_30',
    name: 'Mois de feu',
    description: '30 jours consécutifs',
    icon: '🌋',
    xpReward: 1000,
    rarity: 'epic',
    condition: (p) => p.streak >= 30,
  },
  {
    id: 'streak_100',
    name: 'Centurion de l\'assiduité',
    description: '100 jours consécutifs !',
    icon: '👑',
    xpReward: 5000,
    rarity: 'legendary',
    condition: (p) => p.streak >= 100,
  },
  {
    id: 'perfect_session',
    name: 'Session parfaite',
    description: 'Obtenez 100% de bonnes réponses sur une session',
    icon: '⭐',
    xpReward: 150,
    rarity: 'rare',
    condition: (p) => p.totalCardsReviewed > 0 && p.totalCorrect === p.totalCardsReviewed,
  },
  {
    id: 'import_big',
    name: 'Grand importateur',
    description: 'Importez plus de 50 cartes d\'un coup',
    icon: '📥',
    xpReward: 100,
    rarity: 'common',
    condition: (_p, stats) => stats.totalCards >= 50,
  },
  {
    id: 'import_library',
    name: 'Bibliothèque',
    description: 'Ayez plus de 200 cartes dans votre collection',
    icon: '📖',
    xpReward: 250,
    rarity: 'rare',
    condition: (_p, stats) => stats.totalCards >= 200,
  },
  {
    id: 'level_5',
    name: 'Niveau 5',
    description: 'Atteignez le niveau 5',
    icon: '⚡',
    xpReward: 200,
    rarity: 'common',
    condition: (p) => p.level >= 5,
  },
  {
    id: 'level_10',
    name: 'Niveau 10',
    description: 'Atteignez le niveau 10',
    icon: '💎',
    xpReward: 500,
    rarity: 'rare',
    condition: (p) => p.level >= 10,
  },
  {
    id: 'level_20',
    name: 'Maître',
    description: 'Atteignez le niveau 20',
    icon: '🌟',
    xpReward: 2000,
    rarity: 'legendary',
    condition: (p) => p.level >= 20,
  },
]

export const RARITY_COLORS: Record<string, string> = {
  common: 'from-gray-500 to-gray-600',
  rare: 'from-blue-500 to-indigo-600',
  epic: 'from-purple-500 to-pink-600',
  legendary: 'from-amber-400 to-orange-500',
}

export const RARITY_LABELS: Record<string, string> = {
  common: 'Commun',
  rare: 'Rare',
  epic: 'Épique',
  legendary: 'Légendaire',
}
